### PR TITLE
fix: main player comms reported rotation

### LINKED ISSUE #476: Fix users comms reported rotation
Through comms we always report the CAMERA rotation but we should be reporting the CHARACTER rotation, otherwise when players are using the third person camera, they think the rest of the users see them in the direction they point their avatar but they actually see the rotation of the camera...

### PR DESCRIPTION
**Pull request by pbosio**
Fixes #476

WHY
Through comms we always report the CAMERA rotation but we should be reporting the CHARACTER rotation, otherwise when players are using the third person camera, they think the rest of the users see them in the direction they point their avatar but they actually see the rotation of the camera...

<s>kernel PR need to be merged first: https://github.com/decentraland/kernel/pull/181</s>

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs [hunk 1]
```diff
@@ -532,7 +533,7 @@ void ReportMovement()
         //                  - Scenes not being sent for loading, making ActivateRenderer never being sent, only in WSS mode.
         //                  - Random teleports to 0,0 or other positions that shouldn't happen.
         if (initialPositionAlreadySet)
-            DCL.Interface.WebInterface.ReportPosition(reportPosition, compositeRotation, playerHeight);
+            DCL.Interface.WebInterface.ReportPosition(reportPosition, compositeRotation, playerHeight, cameraRotation);
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs:536]: Please add some tests to avoid future regressions, as this change already broke the client in the past.

**Review by BrianAmadori — CHANGES_REQUESTED** [review]

**Review by AjimenezDCL — APPROVED** [review]

**Comment by kuruk-mm** [comment]
This PR fix https://github.com/decentraland/unity-renderer/issues/1822

**Review by BrianAmadori — APPROVED** [review]
