### PR TITLE
Fix: allow user to play emotes on moving platforms

### LINKED ISSUE #2251: Can't do emotes on platforms
When a player is standing still on a moving platform, they can't perform any emotes

You can see this clearly in genesis plaza
If you get on the floating train or the balloon that take you around the plaza, you can't do any emotes while the platforms move. My avatar is still doing only an idle animation. Once the platforms finish their path and stay still, then you can do emotes.

This would be especially good to have for parades, where players on moving mobiles can dance or wave at the crowds

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #2251
Users can now play emotes on moving platforms

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/platform-anim
2. In genesis plaza go on the air balloon
3. Try to play emotes on it and verify it works
4. Play emotes in other contexts and verify a regular behavior

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs [hunk 1]
```diff
@@ -49,6 +49,7 @@ public class DCLCharacterController : MonoBehaviour
     Vector3 velocity = Vector3.zero;
 
     public bool isWalking { get; private set; } = false;
+    public bool isMoving { get; private set; } = false;
```
Comment (pravusjif) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs:52]: Can we rename this to `isMovingByUserInput` or similar?

**Review by pravusjif — APPROVED** [review]
Nice job, I also think the solution is to bind that emotes escaping to character movement by user input instead of just character movement.
