### PR TITLE
fix: Fix pools prewarming + Explore section loading improvement

### LINKED ISSUE #1728: Pools prewarming is not working correctly
We realized something that was wrongly implemented related to the Pool creation: When we used the `ForcePrewarm()` function (from our `Pool` class) after creating a pool, the number of instantiated objects was half of what was indicated in the `maxPrewarmCount` param. So our Pools system was not working correctly.

### Current code
```
public void ForcePrewarm()
{
   if (maxPrewarmCount <= objectsCount)
      return;

   for (int i = 0; i < Mathf.Max(0, maxPrewarmCount - objectsCount); i++)
   {
      Instantiate();
   }
}
```

### Fix to apply
```
public void ForcePrewarm()
{
   if (maxPrewarmCount <= objectsCount)
      return;

   int objectsToInstantiate = Mathf.Max(0, maxPrewarmCount - objectsCount);
   for (int i = 0; i < objectsToInstantiate); i++)
   {
      Instantiate();
   }
}
```

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #1728 
### Fix pools prewarming
We realized something that was wrongly implemented related to the Pool creation: When we used the `ForcePrewarm()` function (from our `Pool` class) after creating a pool, the number of instantiated objects was half of what was indicated in the `maxPrewarmCount` param.

So our Pools system was not working correctly, in fact in all places where we were using a prewarming, it was always creating the half of objects.

#### The wrong code
```
public void ForcePrewarm()
{
   if (maxPrewarmCount <= objectsCount)
      return;

   for (int i = 0; i < Mathf.Max(0, maxPrewarmCount - objectsCount); i++)
   {
      Instantiate();
   }
}
```

#### The fixed code
```
public void ForcePrewarm()
{
   if (maxPrewarmCount <= objectsCount)
      return;

   int objectsToInstantiate = Mathf.Max(0, maxPrewarmCount - objectsCount);
   for (int i = 0; i < objectsToInstantiate); i++)
   {
      Instantiate();
   }
}
```

### Explore section loading improvement
Also, making use of the Pools system, we have improved the loading of the Explore section in our **Start Menu**. For this purpose we have used the `ForcePrewarm()` function to pre-instantiate some game objects (mostly related to places and events cards) and gain performance on the first opening of the Start Menu.

## How to test the changes?
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/Fix-pools-pre-warming
2. Test the application and confirm everything is working fine.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by lorux0 — APPROVED** [review]
Great work, LGTM!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs [hunk 1]
```diff
@@ -128,14 +128,23 @@ public interface IEventsSubSectionComponentView
     /// Set the current scroll view position to 1.
     /// </summary>
     void RestartScrollViewPosition();
+
+    /// <summary>
+    /// Configure the needed pools for the events instantiation.
+    /// </summary>
+    void ConfigurePools();
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: Does it make sense for this to be in the interface? We could place it in the constructor/awake of the implementations and free the controllers from having to explicitly call this.

**Review by AjimenezDCL — APPROVED** [review]
Approving with a small question

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: In this case I am doing it intentionally, I'm ordering the creation of the pools before the view is activated because I want to have the pools prewarmed and ready before the user opens the Start Menu by first time.

Comment (AjimenezDCL) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: But you could do it in the Awake of each view and they would be prewarmed as well without the controller knowing.

Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: But the Awake is called when the monobehaviour is active, and in this case all the views are hidden until the user open the Start Menu by first time.

Comment (AjimenezDCL) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: Oh you are right!

Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:135]: Anyway thanks for the suggestion, because it is applicable for other cases and I personally sometimes I use to pass too much responsibilities to the controller when they should be in the own view 😄
