### PR TITLE
Fix: show minimap on explore closure

### LINKED ISSUE #2111: Minimap is hidden after explore closure
When we open the explore with a shortcut different from the Map one and then close it with the same button the minimap is not rendered:

Screenshot 2022-04-01 at 11 16 29

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #2111 
Avoids map to be invisibile when closing the explore

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minimap-invisible
2. Open explore with shortcuts
3. Close it
4. Verify minimap is still visible

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs [hunk 1]
```diff
@@ -72,6 +72,7 @@ void Start()
             MapRenderer.OnParcelClicked += TriggerToast;
             MapRenderer.OnCursorFarFromParcel += CloseToast;
             CommonScriptableObjects.playerCoords.OnChange += UpdateCurrentSceneData;
+            DataStore.i.exploreV2.isOpen.OnChange += OnExploreChange;
```
Comment (pravusjif) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs:75]: Should we unsubscribe this in `DataStore.i.exploreV2.isOpen.OnChange` or do you think it's not needed?

**Review by pravusjif — APPROVED** [review]

**Review by Kinerius — APPROVED** [review]
Nice work, I couldn't reproduce the issue anymore.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs (hunk 1 above)
Comment (davidejensen) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs:75]: Fixed, I was unsubbing from the wrong thing, my bad!
