### PR TITLE
fix: The backpack breaks when the owned wearables request fails

### LINKED ISSUE #4167: Null Wearable is added to inventory
https://play.decentraland.zone/?BUILDER_SERVER_URL=https://builder-api.decentraland.zone/v1&NETWORK=goerli&DEBUG_MODE=true&WITH_COLLECTIONS=9c4d923f-3e19-4abc-a012-33397f1e10ea

You will receive a malformed WearablesRequestFailed: `(intermediate value).data.filter is not a function`
The correct structure is:
```
[Serializable]
public class WearablesRequestFailed
{
    public string error;
    public string context;
}
```
So it's impossible to execute:
```
if (requestFailedResponse.context == BASE_WEARABLES_CONTEXT ||
            requestFailedResponse.context.Contains(THIRD_PARTY_WEARABLES_CONTEXT) ||
            requestFailedResponse.context.Contains(OWNED_WEARABLES_CONTEXT))
        {
            ResolvePendingWearablesByContextPromise(
                requestFailedResponse.context,
                null,
                requestFailedResponse.error);
        }
        else
        {
            string[] failedWearablesIds = requestFailedResponse.context.Split(',');
            for (int i = 0; i < failedWearablesIds.Length; i++)
            {
                ResolvePendingWearablePromise(
                    failedWearablesIds[i],
                    null,
                    $"The request for the wearable '{failedWearablesIds[i]}' has failed: {requestFailedResponse.error}");
            }
        }
```
We can prevent an NRE by
```
if (requestFailedResponse?.context == null)
            return;
```

Then you will see:
```
PromiseException: The request for the wearable 'urn:decentraland:off-chain:base-avatars:Espadrilles' has failed: (intermediate value).data.filter is not a function
```
It looks like after that `null` is added to the inventory and causes many other `Null Reference Exception`s and it becomes a blocker.

We should find a place to prevent adding `null` to the inventory

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #4167 

Solves 2 things:

- A NullRef that we were not managing correctly in the `CatalogController.WearablesRequestFailed` method.
- A wrong behavior of the backpack which caused it to stuck when the request of the owned wearables failed.

image

## How to test the changes?
1. Switch your metamask to GOERLI.
2. Go to: https://play.decentraland.zone/?explorer-branch=fix/null-wearable-is-added-to-inventory&BUILDER_SERVER_URL=https://builder-api.decentraland.zone/v1&NETWORK=goerli&DEBUG_MODE=true&WITH_COLLECTIONS=9c4d923f-3e19-4abc-a012-33397f1e10ea
3. Open the backpack.
4. Notice that, even if the owned wearables failed when they were requested, the rest of the backpack (avatar preview and all the rest of wearables) loads correctly.
5. Close the backpack.
6. Notice the user's flow doesn't break.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs [hunk 1]
```diff
@@ -65,7 +65,7 @@ public static void Clear()
         pendingRequestsToSend.Clear();
     }
 
-    //This temporary until the emotes are in the content server 
+    //This temporary until the emotes are in the content server
```
Comment (eordano) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/CatalogController/CatalogController.cs:68]:
```suggestion
    // TODO: when emotes get published to the content server, remove this
```

**Review by kwsskulinski — APPROVED** [review]
Issue seems to be fixed. All available wearables were loaded and user flow did not break.
