### PR TITLE
fix: biw thumbnail bug

### LINKED ISSUE #948: BIW: the thumbnail will stay in scene if you drag NFT(Collectible) assets from catalog to scene

### PR DESCRIPTION
**Pull request by Suduck**
## What does this PR change?

Fix #948 

This PR fixes an issue with the thumbnails of the ground and collectibles when you were dragging and dropping them to the scene

## How to test the changes?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-thumbnail-bug
2. Enter builder in world 
3. Try to drag and drop a collectible, ground and other items to the scene

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/DragAndDropSceneObjectControllerShould.cs [hunk 1]
```diff
@@ -30,5 +52,74 @@ public void ClickCorrectly()
...
+            dragAndDropSceneObjectController.CatalogItemDropped();
+
+            //Assert
+            Assert.IsNotNull(dragAndDropSceneObjectController.itemDroped);
+        }
+
+        private CatalogItemAdapter CreateAdapter()
+        {
+            var adatper = BIWTestHelper.CreateCatalogItemAdapter(mockedGameObject);
+            adatper.SetContent(item);
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Tests/DragAndDropSceneObjectControllerShould.cs:121]:
```suggestion
            adapter.SetContent(item);
```
typo

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/Unpublish/UnpublishPopupController.cs [hunk 2]
```diff
@@ -31,7 +31,7 @@ public void Dispose()
         CoroutineStarter.Stop(fakeProgressRoutine);
         view.OnCancelPressed -= OnCancel;
         view.OnConfirmPressed -= OnConfirmUnpublish;
-        view.Dispose();
+        view?.Dispose();
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuilderProjectsPanel/Scripts/Unpublish/UnpublishPopupController.cs:34]:
```suggestion
        if ( view != null ) view.Dispose();
```
Can we use a normal if here? if view is a unity object the null coalescing operator may fail.

**Review by BrianAmadori — COMMENTED** [review]
Just did a quick review, didn't evaluate the approach.

**Review by AjimenezDCL — APPROVED** [review]
