### PR TITLE
Fix: fixed clickable coordinates in chat

### LINKED ISSUE #4669: Coordinates in chat are not being clickable
This a regression issue. They should be clickable and teleport the current user to the specified location.

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #4669
Fixes clickable coordinates in chat

...

## How to test the changes?

1. Launch the explorer
2. Type some valid coordinates in chat
3. Verify they are highlighted and are clickable without any issues

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/CoordinateUtils.cs [hunk 1]
```diff
@@ -2,7 +2,7 @@
 
 public class CoordinateUtils
 {
-    private const string COORDINATE_MATCH_REGEX = @"(?<!\S)[-]?\d{1,3},[-]?\d{1,3}(?!\S)";
+    private const string COORDINATE_MATCH_REGEX = @"(?<!\w)(?<!<\/noparse>)[-]?\d{1,3},[-]?\d{1,3}(?!\w)(?!<\/\/noparse>)";
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Utils/CoordinateUtils.cs:5]: no need to escape special characters like `\/` since the string is marked with `@`

**Review by lorux0 — APPROVED** [review]
the regex looks good!
