### PR TITLE
fix: biw smart item compatibility

### LINKED ISSUE #744: BIW: smart item compatibility with builder

### PR DESCRIPTION
**Pull request by Suduck**
Fixes #744 
## What does this PR change?

This PR adds the compatibility with builder around smart items so you can load the builder scenes even if they have smart items inside it 

It also include a quick fix

- [x] If you try to enter in builder in world while the scene is still not loaded (from the shorcut) it won't start the builder in world flow 

## How to test the changes?

1. Go to: https://play.decentraland.zone/branch/feat/biw-smart-item-handle/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-fix-bug
2. Open builder in world land with an scene that you has previously created in builder with smart items 
3. Made a change in the scene and open again the scene in the builder
4. All the connections in the smart items should remain

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs [hunk 1]
```diff
@@ -17,6 +17,8 @@ public class DCLName : BaseDisposable
     public class Model : BaseModel
     {
         public string value;
+        //Note: This value is used for builder to manage the smart items, when the builder is no longer active we should remove it
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs:20]: Only as suggestion: I would make this note as a `TO DO` in order to have it more localized in the future.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs [hunk 2]
```diff
@@ -485,6 +485,10 @@ public void TryStartEnterEditMode(bool activateCamera, IParcelScene targetScene
             return;
         }
 
+        //If the scene is still not loaded, we return as we still can't enter in builder in world 
+        if (sceneToEditId != null)
+            return;
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs:490]: Only by curiossity: Why it is necessary to do this check by second time? As I can see, the `FindSceneToEdit()` function is not any kind of coroutine nor an async method... in what case could we get the `sceneToEditId` as null in this point?

**Review by sandrade-dcl — APPROVED** [review]
Good job! Approved! I only left some doubts.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs (hunk 2 above)
Comment (Suduck) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BuilderInWorldController.cs:490]: In the case that we try to enter in the land but the scene is still not loaded, so when we try to find the scene we can't find it since it is not loaded yet, To do this you need to enter with the 'K' key very quickly after we exit.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs (hunk 1 above)
Comment (Suduck) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs:20]: Will do in the current branch that I am working!
