### PR TITLE
Fix: empty world on fresh Desktop start

### LINKED ISSUE #4979: Empty world on fresh Desktop start
The world loads empty when doing a fresh start in the desktop client logging as a guest.

https://images.zenhubusercontent.com/337227404/3f16ba8f-f928-4384-b89d-7a69d5e4dc4f/2023_04_17_09_59_29.mp4

Repro Steps:
1. Uninstall Decentraland desktop client
2. Install Decentraland desktop client
3. Enter with the link: https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=release/release-20230414
4. Select guest

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
Closes #4979,

- Moved logic for hiding Map section in Explore UI from controller to view (that fixed the bug)
- Brought back locking hot key for map when in the world
- Added isWorld bool to the send scene data from the browser-interface

## How to test the changes?

1. Check with the fresh Desktop build that it loads normally
2. Check that map section and hot-key for it is blocked when in the World
3. Check that comming back from the world to the normal realm don't bring additional info inside Map (no POI from World)

- go through url to realm=redeemer.dcl.eth, there is a cube there. If you click the cube -> you should get the destination information 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at 3ed14c8</samp>

Improved logging and minimap functionality for the Unity interface. Added a `defaultLogger` to `UnityInterface.ts` and refined the scene detection logic for the minimap.

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs [hunk 1]
```diff
@@ -87,6 +89,8 @@ public override void Awake()
             { ExploreSection.Quest, questSection },
             { ExploreSection.Settings, settingsSection },
         };
+
+        DataStore.i.common.isWorld.OnChange += OnWorldChange;
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs:93]: We should start moving away from the use of static instances like `DataStore.i` in our classes. In this case we could have some initialization method in the view in order to inject the needed dependencies.

(Maybe it's something that is a bit out of the scope of this PR since there already existed the use of these static instance before your changes, but I wanted to warn it for future improvements)

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs [hunk 2]
```diff
@@ -291,4 +295,17 @@ internal RealmSelectorComponentView ConfigureRealmSelectorModal()
...
+        if (isWorld == wasWorld) return;
+
+        if (isWorld && IsSectionActive(ExploreSection.Map))
+        {
+            placesAndEventsSection.Show();
+            mapSection.Hide();
+        }
+
+        SetSectionActive(ExploreSection.Map, !isWorld);
+    }
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs:310]: I'm wondering if this logic shoulnd't be in the controller side. The views shouldn't have the responsibility of knowing when something related to the world is happening. In my opinion, ideally, the views should only accept orders from controllers or from the UI controls of the own view.

**Review by sandrade-dcl — APPROVED** [review]
Approved with some comments.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs (hunk 2 above)
Comment (popuz) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs]: ok, I moved logic into controller in the new commit

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs (hunk 1 above)
Comment (popuz) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/MainMenu/ExploreV2Menu/ExploreV2MenuComponentView.cs]: Agree. This refactoring for this legacy code should be done together with removing all `DataStore.i.` appearance there. And there are a lot of them, so I will move it our of scope of this PR

**Review by mikhail-dcl — APPROVED** [review]
Looks good to me

**Comment by popuz** [comment]
@dalkia explored one bug with the current approach 

It breaks getting the information of a scene when you are in a world.
- If you check in currently in .org, and you go through url to realm=redeemer.dcl.eth, there is a cube there. If you click the cube, you get the destination information
- If you check with this PR and do the same process, you dont get the info of the scene

**Review by dalkia — APPROVED** [review]
LGTM
