### PR TITLE
fix: Mute scene SFX when Backpack, BiW Editor or Tutorial is open

### LINKED ISSUE #571: Both musics, avatar editor and genesis plaza, playing during Backlog, BiW and Tutorial
During the SignUp process, when we reach the Avatar Editor screen, we're listening 2 musics at the same time: the music of the own Avatar Editor and the background music of the Genesis Plaza.

This is also happening when we open the BiW editor or the Tutorial.

We should mute any kind of sound related to the world while we have open these features.

**Steps to reproduce:**
1. Enter Decentraland as incognito mode.
2. Select the "Enter as Guest" option.
3. When the avatar editor is showed, notice both musics being played.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?

Fixes #571 

If we are on a scene with some music or SFX playing in background (ie: Genesis Plaza), if we open a feature with its own music (ie: **Backpack**, **BiW Editor** or **Tutorial**), we're listening 2 musics at the same time: the music of the feature and the background music of the scene.

Now, we mute any kind of sound related to the scene while we open these features.

## How to test the changes?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/Mute-scene-audio-when-Backpack-BiW-or-Tutorial-is-open&ENV=org
2. Once you are in the Genesis Plaza (or any other scene with background music), open any of these features: **Backpack**, **BiW Editor** or **Tutorial**.
3. Notice that only the music of the feature is playing and the scene-related is muted until you close the feature.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]

**Review by RominaMarchetti — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs [hunk 1]
```diff
@@ -732,6 +733,7 @@ public void ExitEditMode()
 
         biwAudioHandler.gameObject.SetActive(false);
         DataStore.i.appMode.Set(AppMode.DEFAULT);
+        DataStore.i.virtualAudioMixer.sceneSFXVolume.Set(1f);
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs:736]: This shouldn't have into account the last value? I mean, if somewhere else put a value of 0,5f this will override it

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs [hunk 2]
```diff
@@ -539,6 +539,7 @@ public void SetVisibility(bool visible)
 
         if (!visible && view.isOpen)
         {
+            DataStore.i.virtualAudioMixer.sceneSFXVolume.Set(1f);
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs:542]: Same as before

File: unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs [hunk 3]
```diff
@@ -262,6 +263,7 @@ public void SetTutorialDisabled()
 
             tutorialReset = false;
             isRunning = false;
+            DataStore.i.virtualAudioMixer.sceneSFXVolume.Set(1f);
```
Comment (Suduck) [inline unity-renderer/Assets/Tutorial/Scripts/TutorialController.cs:266]: And same as before

**Review by Suduck — APPROVED** [review]
LGTM code wise! I have a concern about the value used. Imagine that the Audio settings panel set a different value there, Will this override that value?

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs:736]: No, this `sceneSFXVolume` is not the value taken by the settings panel but a independent multiplier that is applied to it. If the value in Settings Panel was 0.5, the fact to put this multiplier as 0 and then to 1 will will always keep the original value.

Comment (Suduck) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWMainController.cs:736]: Sounds good!
