### PR TITLE
fix: input spikes when changing lock states

### LINKED ISSUE #1104: First person camera turns to a random direction on pressing ESC
While you are in first person camera, and press ESC key, the camera direction changes to a random one. This does not always happen, but once it does, it happens all the time during that session.

No steps to reproduce.

Before pressing ESC

After pressing ESC

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Fix #1104 

...

## How to test the changes?

Do random stuff on the world and change the focus state often ( pressing ESC and clicking on the screen over different points in the viewport).
Either when locking on or off, the camera shouldn't move abruptly.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+        public void TearDown()
+        {
+            Cursor.lockState = previousLockState;
+        }
+        
+        [TestCase(0, 0)]
+        [TestCase(10, 10)]
+        [TestCase(-10, -10)]
+        [TestCase(0.5f, 0.5f)]
+        public void WhenLockStateIsNotChangedValueWontChange(float inputValue, float expectedInputValue)
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs:27]: "Input spike fixer should when lock state is not changed value wont change" is not a valid english sentence.

I suggest:
"NotChangeValueWhenSameLockStateIsSetTwice"

(or any name that matches the should sentence).

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+        {
+            var inputSpikeFixer = new InputSpikeFixer(() => CursorLockMode.Locked);
+            var returnValue = inputSpikeFixer.GetValue(inputValue);
+            
+            Assert.AreEqual(expectedInputValue, returnValue);
+        }
+        
+        [Test]
+        public void WhenLockStateIsChangedAndValueIsHigherThanToleranceReturnValueIsZero()
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs:36]:
```suggestion
        public void ReturnZeroWhenLockStateIsChangedAndValueIsHigherThanTolerance()
```

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+            var inputSpikeFixer = new InputSpikeFixer(() => lockState);
+            lockState = CursorLockMode.Confined;
+            
+            var returnValue = inputSpikeFixer.GetValue(10);
+            
+            Assert.AreEqual(0, returnValue);
+        }
+        
+        [Test]
+        public void WhenLockStateIsChangedAndValueIsLowerThanToleranceReturnValueIsZeroJustOnce()
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/InputSpikeFixerShould.cs:48]:
```suggestion
        public void ReturnZeroJustOnceWhenLockStateIsChangedAndValueIsLowerThanTolerance()
```

**Review by BrianAmadori — APPROVED** [review]
LGTM. Please address the naming of tests before merging.
