### PR TITLE
fix: BiW entity scale/rotation changes are not always synchronized

### LINKED ISSUE #569: BiW entity scale/rotation changes are not always synchronized
If you rotate/scale an entity and you don't move it, the system won't detect any changes in it and won't update its state

Steps to reproduce:
- Create an entity
- Reescale it in different axis
- Rotate it
- Dont move it
- Exit the editor
- Reenter de editor
- Check entity proportions

* This does not always happen

### PR DESCRIPTION
**Pull request by sandrade-dcl**
### Fixes #569 
If you rotate/scale an entity and you don't move it, the system won't detect any changes in it and won't update its state.

#### Steps to reproduce:
1. Create an entity.
2. Reescale it in different axis.
3. Rotate it.
4. Dont move it.
5. Exit the editor.
6. Reenter de editor.
7. Notice that the changes were not saved.

## How to test it?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-entity-scale-and-rotation-changes-are-not-always-synchronized&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
2. Press 'K' to open the Builer In World editor.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs [hunk 1]
```diff
@@ -147,10 +147,15 @@ public void ReportTransform(bool forceReport = false)
     {
         foreach (DCLBuilderInWorldEntity entity in selectedEntities)
         {
-            if (!entity.HasMovedSinceLastReport() && !forceReport)
+            if (!entity.HasMovedSinceLastReport() &&
+                !entity.HasScaledSinceLastReport() &&
+                !entity.HasRotatedSinceLastReport() &&
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs:152]: Do we need this grade of granularity? I mean , what do you think to unify this methods in `HasTransformChangeSinceLastReport`? (Same for report)

I am ok with both parts, but maybe this can made the code more readeable

**Review by Suduck — APPROVED** [review]
LGTM!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs:152]: Yeah, we could unify all in only one function but, if you don't mind, I would like to keep it separated because I think it could be useful for some future requirements where we need to detect these specifics actions.
