### PR TITLE
fix: Offline friends sometimes don't load

### LINKED ISSUE #4023: Friends does not load for every client
After the latest release, there's been reports of users that friend list does not always load.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #4023 (Point 2 of this issue: `Friends who are offline are not being displayed`)

## Problem
From the second time on we opened the friends window, the offline list was always loading empty.
The problem was that, after re-opening the HUD from a second time and clean its lists, when we received the new list of friends from the backend, when the flow reached the `UpdateFriendshipStatus()` function, we had this condition:
```
if (friends.ContainsKey(userId) && friends[userId].friendshipStatus == friendshipStatus)
    return;
``` 

In this case, as the new friends received already were loaded in our internal dictionary `friends`, the flow was being always canceled and never added the data into the HUD.

The main problem here is that we were using the `UpdateFriendshipStatus()` for managing the request of friends, when this function should be used only to keep updated the status of the already loaded friends.

## Solution
In order to not depend on the `UpdateFriendshipStatus()` flow for getting the list of friends, we have made the `GetFriends()` function in the `FriendsController` as async (`GetFriends()` -> `GetFriendsAsync()`), then the consumer (`FriendsHUDController`) can call it and wait for the response to directly fill the list in the UI.

## How to test the changes?
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/offline-friends-are-not-being-displayed
2. Open the friends list by first time.
3. Check the friends list is loaded correctly.
4. Close the friends list.
5. Open it again.
6. Check the friends list is loaded correctly.
7. Repeat this process several times and check that the lists are being loaded correctly.
8. Check the friends feature is working as expected.

## Important
This has been the quicker solution in order to add the fix in the next release and let the users load their offline friends list correctly, but as a second step we should synchronize with dService team in order to create a new RPC function for the current `GetFriends` approach. With these changes, it should be something very easy to adapt.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs [hunk 1]
```diff
@@ -146,11 +145,23 @@ public async UniTask<FriendRequest> RejectFriendshipAsync(string friendRequestId
         public void RemoveFriend(string friendId) =>
             apiBridge.RemoveFriend(friendId);
 
-        public void GetFriends(int limit, int skip) =>
-            apiBridge.GetFriends(limit, skip);
+        public async UniTask<string[]> GetFriendsAsync(int limit, int skip, CancellationToken ct)
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs:148]: lets rename to `cancellationToken` instead of `ct` for both overloads

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs [hunk 2]
```diff
@@ -22,8 +22,8 @@ public interface IFriendsApiBridge
         void RejectFriendship(string userId);
         UniTask<RejectFriendshipPayload> RejectFriendshipAsync(string friendRequestId);
         void RemoveFriend(string userId);
-        void GetFriends(int limit, int skip);
-        void GetFriends(string usernameOrId, int limit);
+        UniTask<AddFriendsPayload> GetFriendsAsync(int limit, int skip, CancellationToken ct);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs:25]: its a common practice to set the cancellation token with a default value: `CancellationToken cancellationToken = default`

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs [hunk 3]
```diff
@@ -45,8 +45,8 @@ public interface IFriendsController
         UniTask<SocialFriendRequest> RejectFriendshipAsync(string friendRequestId);
         bool IsFriend(string userId);
         void RemoveFriend(string friendId);
-        void GetFriends(int limit, int skip);
-        void GetFriends(string usernameOrId, int limit);
+        UniTask<string[]> GetFriendsAsync(int limit, int skip, CancellationToken ct);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs:48]: its a common practice to set the cancellation token with a default value: `CancellationToken cancellationToken = default`

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs [hunk 4]
```diff
@@ -146,11 +145,23 @@ public async UniTask<FriendRequest> RejectFriendshipAsync(string friendRequestId
...
+            AddFriends(payload.friends);
 
-        public void GetFriends(string usernameOrId, int limit) =>
-            apiBridge.GetFriends(usernameOrId, limit);
+            return payload.friends;
+        }
+
+        public async UniTask<string[]> GetFriendsAsync(string usernameOrId, int limit, CancellationToken ct)
+        {
+            var payload= await apiBridge.GetFriendsAsync(usernameOrId, limit, ct);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs:159]: it is not needed to switch to main thread after this operation?

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs [hunk 5]
```diff
@@ -146,11 +145,23 @@ public async UniTask<FriendRequest> RejectFriendshipAsync(string friendRequestId
         public void RemoveFriend(string friendId) =>
             apiBridge.RemoveFriend(friendId);
 
-        public void GetFriends(int limit, int skip) =>
-            apiBridge.GetFriends(limit, skip);
+        public async UniTask<string[]> GetFriendsAsync(int limit, int skip, CancellationToken ct)
+        {
+            var payload = await apiBridge.GetFriendsAsync(limit, skip, ct);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs:150]: it is not needed to switch to main thread after this operation?

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs [hunk 6]
```diff
@@ -41,21 +42,18 @@ public void Initialize()
         [Test]
         public void AddFriends()
         {
-            var updatedFriends = new Dictionary<string, FriendshipAction>();
-            var totalFriends = 0;
-            controller.OnUpdateFriendship += (s, action) => updatedFriends[s] = action;
-            controller.OnTotalFriendsUpdated += i => totalFriends = i;
-
-            apiBridge.OnFriendsAdded += Raise.Event<Action<AddFriendsPayload>>(
+            _ = apiBridge.GetFriendsAsync(Arg.Any<int>(), Arg.Any<int>(), Arg.Any<CancellationToken>()).Returns(UniTask.FromResult(
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs:45]: no need for `_ =` right?

**Review by lorux0 — CHANGES_REQUESTED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs]: Done!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs (hunk 2 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsApiBridge.cs]: Done!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs (hunk 3 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/IFriendsController.cs]: Done!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs (hunk 4 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs]: It is not needed but the IDE gives you a warning due to this.

Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs]: Yes! I forgot it! Done, thanks!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs (hunk 5 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs]: Yes! I forgot it! Done, thanks!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs (hunk 6 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs:45]: It is not really needed but the IDE suggest you to do it in a warning.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs [hunk 7]
```diff
@@ -187,12 +185,14 @@ public void UpdateUserPresence()
         {
             var updatedFriends = new Dictionary<string, UserStatus>();
             controller.OnUpdateUserStatus += (s, status) => updatedFriends[s] = status;
-            apiBridge.OnFriendsAdded += Raise.Event<Action<AddFriendsPayload>>(
+
+            _ = apiBridge.GetFriendsAsync(Arg.Any<int>(), Arg.Any<int>(), Arg.Any<CancellationToken>()).Returns(UniTask.FromResult(
```
[the remark this answers is not in the document]
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/Tests/FriendsControllerShould.cs:189]: It is not really needed but the IDE suggest you to do it in a warning.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs [hunk 8]
```diff
@@ -33,8 +33,18 @@ public partial class WebInterfaceFriendsApiBridge : MonoBehaviour, IFriendsApiBr
             OnFriendNotFound?.Invoke(name);
 
         [PublicAPI]
-        public void AddFriends(string json) =>
-            OnFriendsAdded?.Invoke(JsonUtility.FromJson<AddFriendsPayload>(json));
+        public void AddFriends(string json)
+        {
+            var payload = JsonUtility.FromJson<AddFriendsPayload>(json);
+            string messageId = "GetFriendsRequest";
```
[the remark this answers is not in the document]
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs]: Done!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs [hunk 9]
```diff
@@ -157,12 +167,26 @@ public void RemoveFriend(string userId)
             });
         }
 
-        public void GetFriends(int limit, int skip) =>
+        public UniTask<AddFriendsPayload> GetFriendsAsync(int limit, int skip, CancellationToken ct)
+        {
+            var task = new UniTaskCompletionSource<AddFriendsPayload>();
+
+            pendingRequests["GetFriendsRequest"] = task;
```
[the remark this answers is not in the document]
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/WebInterfaceFriendsApiBridge.cs]: Done!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs [hunk 10]
```diff
@@ -38,6 +40,8 @@ public class FriendsHUDController : IHUD
         public event Action OnClosed;
         public event Action OnViewClosed;
 
+        private CancellationTokenSource cts = new CancellationTokenSource();
```
[the remark this answers is not in the document]
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs]: Done!

**Review by lorux0 — APPROVED** [review]
great work!

**Review by kwssbocian — APPROVED** [review]
Fix implemented correctly.
✔️After multiple closing and reopening the friends list always loads correctly.
✔️No changes to the functionality of the Friends feature and friend request flow observed.
