### PR TITLE
fix: Welcome to Genesis plaza should not be shown outside of it

### LINKED ISSUE #3087: Welcome screen displayed outside of Genesis Plaza
**Description:**
Loading into the platform with spawn coordinates set outside of Genesis Plaza, results in the Welcome screen being displayed outside of it when spawning with a newly created avatar.

**Steps to reproduce:**

1. Clear Decentraland's cache or open the incognito mode.
2. Load the Decentraland's Web Client.
3. Set the spawn coordinates outside of the Genesis Plaza and reload the page ( ex.: https://play.decentraland.org/?realm=baldr&position=149%2C149&island=Ib4qg ).
4. Load into the platform as a guest.
5. Create a new avatar and accept the Terms of Service.
6. Wait for the platform to load.
7. Observe the issue.

**Results:**
The Welcome screen is displayed for the user when loading to a location outside of Genesis Plaza with a new avatar.

**Expected results:**
The Welcome screen is not displayed if a new avatar is spawned outside of Genesis Plaza. Alternatively, all new avatars are forced to spawn at Genesis Plaza.

**Notes:**

- The issue occurs only when creating a new character.

- The issue occur on both the production and development configurations.

- Please see the attached video for reference: https://images.zenhubusercontent.com/337227404/95433b2b-ed02-409f-a61f-48858bd230d5/_3087.mp4.

- Platforms: Web Client.

### PR DESCRIPTION
**Pull request by PalauiDCL**
fixes #3087 

This PR should avoid the tutorial from being fired outside genesis plaza.

QA

In order to check, reproduce the steps described in the linked issue, the tutorial should not be shown anymore.

### CODE REVIEW

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
Fix failed. The welcome screen and the tutorial are displayed when loading into a location outside of Genesis Plaza.


@kwspgoliasz I made a correction for only plaza genesis, I could not find this issue anymore from my side, hope this time is corrected for real ^^, thank you!

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
When creating a new character, the welcome screen for Genesis Plaza is still displayed at other locations. The information provided in the ticket [#3087](https://github.com/decentraland/unity-renderer/issues/3087) is still valid.

File: unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs [hunk 1]
```diff
@@ -24,8 +24,15 @@ public class TutorialStep_GenesisGreetings : TutorialStep
 
         public override void OnStepStart()
         {
+            Vector2Int currentCoords = CommonScriptableObjects.playerCoords.Get();
+            if (Mathf.Abs(currentCoords.x) > 3 || Mathf.Abs(currentCoords.y) > 3)
+            {
+                Destroy(gameObject);
```
Comment (lorux0) [inline unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs:30]: it would be better to terminate the tutorial through a method of the base class instead of destroying the gameObject through a child class, since it could disrupt the flow

File: unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs [hunk 2]
```diff
@@ -49,6 +49,13 @@ public override void OnStepStart()
                     WebInterface.SendSceneExternalActionEvent(Environment.i.world.state.GetCurrentSceneId(), "tutorial", "begin");
                 }
             }
+
+            Vector2Int currentCoords = CommonScriptableObjects.playerCoords.Get();
+            if (Mathf.Abs(currentCoords.x) > 3 || Mathf.Abs(currentCoords.y) > 3)
```
Comment (Kinerius) [inline unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs:54]: Can you extract this magic number to a constant? :D

**Review by Kinerius — CHANGES_REQUESTED** [review]

**Review by Kinerius — APPROVED** [review]

**Review by kwspgoliasz — APPROVED** [review]
The feature appears to be implemented correctly. The welcome screen functions accordingly with the present design.

File: unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs [hunk 3]
```diff
@@ -63,10 +64,24 @@ public override void OnStepFinished()
...
         }
 
         internal void OnOkButtonClick() { stepIsFinished = true; }
+
+        private void Update()
+        {
+            if (stepIsFinished)
+                return;
+
+            Vector2Int currentCoords = CommonScriptableObjects.playerCoords.Get();
```
Comment (lorux0) [inline unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs:78]: i think you can subscribe to the changes of the `playerCoords` variable instead of polling the object in an update. Let me know what do you think

Comment (PalauiDCL) [reply unity-renderer/Assets/Tutorial/Scripts/Steps/Initial/TutorialStep_GenesisGreetings.cs:78]: Completely agree, will update this before merging
