### PR TITLE
fix: [BiW Editor] UI polishment (Part 2)

### LINKED ISSUE #526: BiW Editor scaling breaks while switching Snapping
Scaling of an entity breaks while swithcing the snapping mode during scaling

Steps to reproduce:
- [ ] Create a new entity in the editor
- [ ] Start editing with scale tool
- [ ] Move the any scale axis and them push Shift to alternate Snapping mode
- [ ] Contemplate scaling aberrations.

### LINKED ISSUE #568: BiW UI polishment part 2
- [x] Builder Panel tooltips look wrong

- [x] Hidden and locked items names need to be greyed out in the Entity List.

- [x] Reset command should be greyed out if no entity is selected in Extra Actions

- [ ] Editing position, rotation and scale in the Entity detailes should bring the same editing input styles as the name editing.

- [x] Some tooltips aligment are wrong

- [x] Extra actions button should dissappear while clicking anywhere else

- [x] Collections and Entity List should be unfolded by default.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
### Fixes #568 
- [x] Builder Panel tooltips look wrong

- [x] Hidden and locked items names need to be greyed out in the Entity List.
- [x] Reset command should be greyed out if no entity is selected in Extra Actions
- [x] Editing position, rotation and scale in the Entity detailes should bring the same editing input styles as the name editing.

- [x] Some tooltips aligment are wrong

- [x] Extra actions button should dissappear while clicking anywhere else

- [x] Collections and Entity List should be unfolded by default.

### Fixes #526 
- [x] If you click open the extra buttons and click on one, you will need to double click the extra button to show them.

## How to test it?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-UI-polishment-Part-2&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=80,154
2. Press 'K' to open the Builer In World editor.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by Suduck — CHANGES_REQUESTED** [review]
Small request!

This tooltip is still not aligned correctly 
image

Also, can we make this gray a little more white? So we can give feedback while you can read it clearly
image

**Comment by Suduck** [comment]
Also, you can't rename a grayed out name

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs [hunk 1]
```diff
@@ -36,6 +36,9 @@ private void Start()
             {
                 Rename(newText);
                 SetTextboxActive(false);
+
+                if (EventSystem.current != null && !EventSystem.current.alreadySelecting)
+                    EventSystem.current?.SetSelectedGameObject(null);
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs:41]: The null propagation is not really needed since we are checking it.

**Review by AjimenezDCL — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Scripts/GodMode/Inspector/EntityListAdapter.cs]: You're right! Thanks! Fixed on https://github.com/decentraland/unity-renderer/pull/635/commits/85e8fc9af0249407d6ec544417c21feb420912a6

**Comment by sandrade-dcl** [comment]
> Small request!
> 
> This tooltip is still not aligned correctly
> image
> 
> Also, can we make this gray a little more white? So we can give feedback while you can read it clearly
> image

Done in https://github.com/decentraland/unity-renderer/pull/635/commits/8807d6d19dfb5584bdd95ce6c95d3ee3367932d8. Thanks!

**Review by Suduck — APPROVED** [review]
