### PR TITLE
fix: the profile picture display the full image of the avatar

### LINKED ISSUE #5967: [QA] Chrome | The profile picture display the full image of the avatar.
## Severity:
SEV-5 | Cosmetics issue
## **Description:**
During the flow of the sing in, if the avatar is customized, we see that the avatar profile picture is displaying the full body instead of just the head.

**Expected result:**
The profile picture display only the head of the avatar.

Screenshot at Nov 20 09-28-59

**Actual result:** 
The profile picture display the full body image of the avatar.

image (4)

## Operating system:
MacOs 14.0
## Error:
null
## Browser (version):
CHROME
## Steps to reproduce:
1. Launch Chrome
2. Log in as guest
3. customize your avatar (body shape, hair style and color, change the clothes)
4. Complete the sign in flow
5. Observe the profile picture once the world has been loaded

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #5967 

During the flow of the sing in, if the avatar was customized, we saw that the avatar profile picture was displayed as the full body instead of just the head.

image (4)

Now the avatar snapshot is saved correctly:

Screenshot at Nov 20 09-28-59

## How to test the changes?
1. Launch the explorer as guest.
2. You should enter in the SignIn flow.
3. Apply several changes in your avatar during the avatar customization process. (body shape, hair style and color, change the clothes)
4. Go to the next screen and accept the terms and conditions.
5. Check that, after the world is loaded, your profile picture shows only the face of your customized avatar.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 48e28b9</samp>

This pull request adds a new flag `isWaitingToBeSavedAfterSignUp` to the backpack data store and the HUD controllers for the backpack editor and the signup flow. The flag is used to trigger a terms of service agreement step before saving the backpack in the signup process. The HUD controllers are updated to subscribe and react to the flag changes.

### CODE REVIEW

**Comment by sandrade-dcl** [comment]
@Ludmilafantaniella you can re-test, I've fixed it.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs [hunk 1]
```diff
@@ -51,6 +51,7 @@ public class SignupHUDController : IHUD
             this.browserBridge = browserBridge;
             this.subscriptionsAPIService = subscriptionsAPIService;
             loadingScreenDataStore.decoupledLoadingHUD.visible.OnChange += OnLoadingScreenAppear;
+            DataStore.i.backpackV2.isWaitingToBeSavedAfterSignUp.OnChange += OnTermsOfServiceAgreedStepAfterSaveBackpack;
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs:54]: inject the datastore instead of referring to the singleton

**Review by lorux0 — APPROVED** [review]

**Comment by lorux0** [comment]
I dont really feel confortable on the back and forth from signup to backpack through datastore. Perhaps an interface for saving the profile could have been injected into the signup? Anyway im approving

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SignupHUD/SignupHUDController.cs:54]: true! On it!

**Comment by Kinerius** [comment]
> I dont really feel confortable on the back and forth from signup to backpack through datastore. Perhaps an interface for saving the profile could have been injected into the signup? Anyway im approving

I agree, we rely too much on singletons there
