### PR TITLE
fix: TextMeshPro materials used by TextShape are not properly destroyed

### LINKED ISSUE #772: TextMeshPro materials used by TextShape are not properly destroyed
There were lots of mesh count related to TextMeshPro on unity's profiler.
We should analyze if the `TextShape` component is destroyed correctly

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?

Fix #772 

There were lots of mesh count related to TextMeshPro on unity's profiler.
We should analyze if the TextShape component is destroyed correctly

## Implemented solution
1. Each time a `TextShape` object is created, we store a copy of the shared material in a private variable.
2. Instead of using `text.fontMaterial...`, we use `text.fontSharedMaterial...` in order to not to provoke new copies of the material.
3. Once the `TextShape` object is destroyed, we destroy our stored material.

**NOTE:** Making different tests with the `TextShape` components loading isolated, I have not seen a huge memory saving (the most important issue that I've detected with the number of materials in the profiler has been telated to this other [ISSUE](https://github.com/decentraland/unity-renderer/issues/876)). Anyway, in order to avoid problems with the material handling, I think it is the best way to manage the cleaning of font materials.

## Test link
https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/TextShape-memory-leaks&ENV=org

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs [hunk 1]
```diff
@@ -62,8 +62,14 @@ public class Model : BaseModel
         public TextMeshPro text;
         public RectTransform rectTransform;
         private Model cachedModel;
+        private Material cachedFontMaterial;
```
Comment (pbosio) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:65]: I think probably a better name would be `fontMaterial` removing de `cached` part

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs [hunk 2]
```diff
@@ -62,8 +62,14 @@ public class Model : BaseModel
...
 
-        private void Awake() { model = new Model(); }
+        private void Awake()
+        {
+            model = new Model();
+            cachedFontMaterial = new Material(text.fontSharedMaterial);
+            text.fontSharedMaterial = cachedFontMaterial;
```
Comment (pbosio) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:71]: Probably is cleaner this way:
```suggestion
            cachedFontMaterial = text.fontMaterial;
```
since `text.fontMaterial` is already creating a new material and assigning it to the `TextMeshPro`

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs [hunk 3]
```diff
@@ -130,24 +136,24 @@ public static IEnumerator ApplyModelChanges(IParcelScene scene, TMP_Text text, M
...
+                text.fontSharedMaterial.EnableKeyword("OUTLINE_ON");
                 text.outlineWidth = model.outlineWidth;
                 text.outlineColor = model.outlineColor;
             }
-            else if (text.fontMaterial.IsKeywordEnabled("OUTLINE_ON"))
+            else if (text.fontSharedMaterial.IsKeywordEnabled("OUTLINE_ON"))
             {
-                text.fontMaterial.DisableKeyword("OUTLINE_ON");
+                text.fontSharedMaterial.DisableKeyword("OUTLINE_ON");
             }
```
Comment (pbosio) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:157]: If you are already holding an instance of the material it would be better to use that directly
i.e: 
```
cachedFontMaterial.EnableKeyword("UNDERLAY_ON");
cachedFontMaterial.SetColor("_UnderlayColor", model.shadowColor);
cachedFontMaterial.SetFloat("_UnderlaySoftness", model.shadowBlur);
```

**Review by pbosio — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs (hunk 2 above)
Comment (BrianAmadori) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:71]: I'd prefer not relying on the `fontMaterial` awful copying mechanism. It's easier to understand as it is now.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs (hunk 1 above)
Comment (BrianAmadori) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:65]: This can conflate with `text.fontMaterial` making the code harder to read.

**Review by BrianAmadori — APPROVED** [review]
LGTM

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs (hunk 3 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs:157]: We can't do it directly because the `ApplyModelChanges` function is static but not our `cachedFontMaterial` variable. We could pass the `cachedFontMaterial` variable through the function signature but, in order not to make the function more complex, I prefeer to continue using `text.fontSharedMaterial`.
