### PR TITLE
fix: performance optimizations when user has many friends

### LINKED ISSUE #2340: Limit the amount of friends in the list
Some users have many friends to list and/or many pending friend requests (more than 1k), pushing the limits of the webgl application. To solve this issue we could:

- [x] load/unload friend's profile pictures on demand depending on what is visible in the scroll
- [x] throttle the load of friend request to avoid hiccups
- [x] improve list sorting & layout updating to avoid hiccups
- [x] searching friends on the search bar should query all the friends, no matter if they are displayed or not

Limit friend entries:

- [x] load a maximum of 50 entries at start
- [x] online friends has no limit
- [x] add a button `show more` at the bottom of the scroll. Whenever you click it, it will load 30 entries
- [x] add a label at the bottom of the scroll saying something like: `(n) hidden friends, use the search bar to find them`
- [x] friend requests should have the same behaviour

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

`closes #2340 `

Some users have many friends to list and/or many pending friend requests (more than 1k), pushing the limits of the webgl application. To solve this issue:

-  load/unload friend's profile pictures on demand depending on what is visible in the scroll.
-  throttle the load of friend request to avoid hiccups.
-  improve list sorting & layout updating to avoid hiccups.
-  searching friends on the search bar should query all the friends, no matter if they are displayed or not.

Limit friend entries:

-  load a maximum of 50 entries at start
-  online friends has no limit
-  add a button show more at the bottom of the scroll. Whenever you click it, it will load 30 entries
-  friend requests should have the same behaviour

### Friends tab
1. 50+ friends is required
2. Open the friends window, there should be a maximum of 50 friends displayed.
3. The rest of the friends can be loaded when clicking "show more" button.
4. Use the search bar to find any friend. It should be displayed correctly.
5. Clean the search bar input. All friends should be displayed correctly.
6. Scroll down & up the list. Profile pictures should be loaded according to what is visible in the list.
7. After you load all the friends, "show more" button should be hidden.

### Friend requests tab
1. 50+ pending received requests is required.
2. Open the friends window, then click on requests tab.
3. There should be a maximum of 50 requests displayed.
4. The rest of the friends can be loaded when clicking "show more" button.
5. Scroll down & up the list. Profile pictures should be loaded according to what is visible in the list.
6. After you load all the requests, "show more" button should be hidden.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs [hunk 1]
```diff
@@ -147,31 +162,61 @@ public void Hide()
...
-                Debug.LogError($"UpdateFriendshipStatus not supported: {friendshipAction}");
+                Debug.LogError($"FriendshipAction not supported: {friendshipAction}");
                 break;
         }
     }
 
-    public void Search(string userId) => FilterFriends(userId);
+    public void Set(string userId, FriendshipStatus friendshipStatus, FriendEntryModel model)
+    {
+        Debug.Log($"Set {userId}, {friendshipStatus}, {model.userName}");
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs:195]: We want to leave this debug log here for some reason?

**Review by sandrade-dcl — APPROVED** [review]
LGTM! Good work, Nico!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs (hunk 1 above)
Comment (lorux0) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDComponentView.cs:195]: no! thank you for checking it, it was a debugging thing
