### PR TITLE
minor fixes in minimap new panel

### LINKED ISSUE #2120: Improvements for minimap new menu
Screenshot 2022-04-04 at 13 45 54

improvements to be applied: 
* Clicking on the 3 dots doesn't produce a sound
* Clicking outside the box should close the menu

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #2120 
Adds sound effects to three dots button, closes the new panel when the cursor gets locked again (same behavior as taskbar panels)

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/minimap-menu-improvs
2. Verify the sound effects on the minimap menu button
3. Lock the mouse and verify that the panel closes itself

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by AjimenezDCL — APPROVED** [review]

**Review by Suduck — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs [hunk 1]
```diff
@@ -76,4 +86,9 @@ public void SetVisibility(bool visible)
         else if (!visible && mainShowHideAnimator.isVisible)
             mainShowHideAnimator.Hide();
     }
+
+    private void OnDestroy()
+    {
+        mouseCatcher.OnMouseLock -= OnMouseLocked;
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs:92]:
```suggestion
        mouseCatcher?.OnMouseLock -= OnMouseLocked;
```

We are checking `mouseCatcher` for `null` above, if the value is nullable we have to check it here as well.

**Review by AjimenezDCL — APPROVED** [review]
