### PR TITLE
fix: disable scrollwheel camera change when mouse on UI element

### LINKED ISSUE #1888: Avoid first/third person scrollwheel change when over UI element
When the cursor is over an UI element the scrollwheel should not change from first to third person and vice versa

### PR DESCRIPTION
**Pull request by DavideJensen**
## What does this PR change?

Fix #1888
Avoid camera change when using mouse scrollwheel and cursor over an UI element

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/disable-scrollwheel-when-ui-mouseover
2. Scroll in and out to change from first to third person camera
3. Place the cursor above an UI element
4. Scroll in and out and verify that the camera mode doesn't change

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by RominaMarchetti — APPROVED** [review]
Amazing! <3

**Review by nlorux — APPROVED** [review]
works great, good job!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs [hunk 1]
```diff
@@ -551,5 +551,16 @@ public static bool TryFindChildRecursively(this Transform transform, string name
             }
             return false;
         }
+
+        public static bool IsPointerOverUIElement(Vector3 mousePosition)
```
Comment (nlorux) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs:555]: perhaps this could be an extension method for future usages

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs [hunk 2]
```diff
@@ -551,5 +551,16 @@ public static bool TryFindChildRecursively(this Transform transform, string name
...
+        {
+            var eventData = new PointerEventData(EventSystem.current);
+            eventData.position = mousePosition;
+            var results = new List<RaycastResult>();
+            EventSystem.current.RaycastAll(eventData, results);
+            return results.Count > 1;
```
Comment (pravusjif) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs:561]: Maybe you already tried but I'd like to know, could we avoid the raycast and list creation with any of the following checks? (Maybe they don't work in this case)

`EventSystem.current.currentSelectedGameObject != null`
or
`EventSystem.current.alreadySelecting`
or
`EventSystem.current.IsPointerOverGameObject()`
