### PR TITLE
fix: biw analytics improvements

### LINKED ISSUE #919: BIW: Screen size analytic is not reported correctly
The event is not sent correctly

### PR DESCRIPTION
**Pull request by Suduck**
## What does this PR change?

Fix #919

This PR fix some biw analytics that werent' send correctly and improve the scene limits event

Analytics fixed: 
-"Player Open Builder in world Panel" now the event is sent correctly
-Scene size value of all events is now correct

## How to test the changes?

1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/biw-analytics
2. Open de builder in world panel
3. Check in the network tab that the scene is send correctly
4. Enter builder in world
5. Check that the scene size is sent correctly
6. Overpass the scene limits
7. Check that the the event now includes the scene limit and an array with the limit overpass

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs [hunk 1]
```diff
@@ -104,10 +104,12 @@ public static void EndScenePublish(SceneMetricsModel sceneLimits, string success
         SendEditorEvent("end_scene_publish", events);
     }
 
-    public static void SceneLimitsOverPassed(SceneMetricsModel sceneLimits)
+    public static void SceneLimitsOverPassed(SceneMetricsModel sceneUsage, SceneMetricsModel sceneLimits)
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs:107]: "overpass" is a single word. Beware of wording here, as "overpass" is negative and "passed" is positive. I see that this method also sends "limit_passed" and this can contradict the meaning depending on intent. 

Maybe we can find a less confusing set of words here?

```suggestion
    public static void SceneLimitsOverpassed(SceneMetricsModel sceneUsage, SceneMetricsModel sceneLimits)
```

Comment (Suduck) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Analytics/BIWAnalytics.cs:107]: Changed to `SceneLimitsExceeded`

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs [hunk 2]
```diff
@@ -29,6 +31,7 @@ protected override void OnEntityRemoved(IDCLEntity e)
             SubstractMetrics(e);
             model.entities = entitiesMetrics.Count;
         }
+        CheckSceneLimitOverPassedAnalaytics();
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs:34]:
```suggestion
        CheckSceneLimitExceededAnalytics();
```

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs [hunk 3]
```diff
@@ -7,6 +7,8 @@
 
 public class BIWSceneMetricsController : SceneMetricsController
 {
+    private string currentOverpassLimitTypes = "";
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs:10]:
```suggestion
    private string currentExceededLimitTypes = "";
```

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs [hunk 4]
```diff
@@ -44,5 +47,24 @@ protected override void OnEntityMeshInfoUpdated(IDCLEntity entity)
...
             model.entities = entitiesMetrics.Count;
         }
+        CheckSceneLimitOverPassedAnalaytics();
+    }
+
+    private void CheckSceneLimitOverPassedAnalaytics()
+    {
+        if (!IsInsideTheLimits())
+        {
+            string overpassLimit = BIWAnalytics.GetLimitsPassedArray(scene.metricsController.GetModel(), scene.metricsController.GetLimits());
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs:57]:
```suggestion
            string exceededLimit = BIWAnalytics.GetLimitsPassedArray(scene.metricsController.GetModel(), scene.metricsController.GetLimits());
```

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs [hunk 5]
```diff
@@ -44,5 +47,24 @@ protected override void OnEntityMeshInfoUpdated(IDCLEntity entity)
...
+            if (overpassLimit != currentOverpassLimitTypes)
+            {
+                BIWAnalytics.SceneLimitsExceeded(scene.metricsController.GetModel(), scene.metricsController.GetLimits());
+                currentOverpassLimitTypes = overpassLimit;
+                Debug.Log("Send overpass limit" + currentOverpassLimitTypes);
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/BIWSceneMetricsController.cs:62]:
```suggestion
                Debug.Log("Send exceeded limit" + currentExceededLimitTypes);
```

**Review by BrianAmadori — APPROVED** [review]
Left some minor remarks, did a small review pass and LGTM so far.

**Review by AjimenezDCL — APPROVED** [review]
