### PR TITLE
fix: reduced ReportAvatarPosition overhead

### LINKED ISSUE #2701: AvatarReporterController performance improvement
# What

`AvatarReporterController` contains a method called `GetcurrentSceneIdNonAlloc` that gets the scene ID by iterating over all loaded scenes and checking if they contain that parcel position to return its ID, this is slow and allocates a lot of memory if we have lots of avatars on the scene.

# How

We have to maintain a new Dictionary<Vector2Int, string> that should contain all the current parcel positions with their respective scene ID, we have to update this dictionary every time a scene gets loaded/unloaded, we are going to avoid multiple iterations and allocations per frame, this may bring us a performance boost when there lots of nearby avatars.

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

`AvatarReporterController.ReportAvatarPosition` had a small overhead and allocations, those are gone.

Fixes #2701 

## How to test the changes?

Scenes with `onEnterSceneObservable` and `onLeaveSceneObservable` should work properly. 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

## Performance Data

# OLD
67 players (-100,126 ) 30 seconds WITHOUT UI (pressing U)
```
 * PERFORMANCE SCORE (0-100) -> 10
 * lowest frame time -> 61.7ms
 * average frame time -> 77.4ms
 * highest frame time -> 100.0ms
 * 1 percentile frame time -> 64.3ms
 * 50 percentile frame time -> 74.4ms
 * 99 percentile frame time -> 100.0ms
 * error percentage -> ±1.3%
 * total hiccups (>0.05ms frames) -> 387 (99.74% of frames were hiccups)
 * total hiccups time (seconds) -> 29.94901
 * total frames -> 388
 * total frames time (seconds) -> 30.0292
```

# NEW
67 players (-100,126 ) 30 seconds WITHOUT UI (pressing U)
```
 * PERFORMANCE SCORE (0-100) -> 11
 * lowest frame time -> 60.8ms
 * average frame time -> 74.5ms
 * highest frame time -> 100.0ms
 * 1 percentile frame time -> 62.2ms
 * 50 percentile frame time -> 70.6ms
 * 99 percentile frame time -> 100.0ms
 * error percentage -> ±1.5%
 * total hiccups (>0.05ms frames) -> 402 (99.75% of frames were hiccups)
 * total hiccups time (seconds) -> 29.94498
 * total frames -> 403
 * total frames time (seconds) -> 30.0436
```

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs [hunk 1]
```diff
@@ -261,6 +261,16 @@ public void DebugBotsInstantiation()
...
+        
+        [ContextMenu("Instantiate 50 bots at player coordinates")]
+        public void DebugBotsInstantiation2()
+        {
+            InstantiateBotsAtCoords("{ " +
+                                    "\"amount\":50, " +
+                                    "\"areaWidth\":15, " +
+                                    "\"areaDepth\":15 " +
+                                    "}");
+        }
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/DebugController/DebugBridge.cs:273]: I believe this should be removed

File: unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IWorldState.cs [hunk 2]
```diff
@@ -2,13 +2,15 @@
...
 using DCL.Models;
+using UnityEngine;
 
 namespace DCL
 {
     public interface IWorldState : ISceneHandler, IService
     {
         HashSet<string> readyScenes { get; set; }
         Dictionary<string, IParcelScene> loadedScenes { get; set; }
+        Dictionary<Vector2Int, string> loadedScenesByCoordinate { get; set; }
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IWorldState.cs:13]: I'm a bit concerned about this 2 collections not being synced. Maybe we should add/remove/update values there in a method and avoid direct access.

**Review by AjimenezDCL — APPROVED** [review]
Looks good, left a small concern!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IWorldState.cs (hunk 2 above)
Comment (Kinerius) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/Interfaces/IWorldState.cs:13]: yeah I was about to make them private so we have proper get and sets but that was going to be a big refactor, if you agree we can do it :)
