### PR TITLE
fix: BiW - Snapping improvements

### LINKED ISSUE #387: BiW Editor snapping should be more responsive
- [x] Moving an item using the gizmos with the snapping active should move it in increments of 0.5
- [x] Snapping mode should snap the entity to the absolute grid and not be relative to the entity position.
- [x] Change sensibility while dragging the entities using the gizmos (it should start sooner)

### LINKED ISSUE #438: Dragging an entity in the scene does not allow snapping switch
If you try to move an entity in the scene by clicking and dragging it, the SHIFT switch for snapping is not working

### PR DESCRIPTION
**Pull request by sandrade-dcl**
### Fixes #387 
Snapping mode should snap the entity to the absolute grid and not be relative to the entity position.

### Fixes #438
If you try to move an entity in the scene by clicking and dragging it, the SHIFT switch for snapping is not working.

## How to test it?
1. Go to: https://play.decentraland.zone/index.html?renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-snapping-improvements&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
2. Press 'K' to open the Builer In World editor.
3. Play with the snapping.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderTranslateGizmo.cs [hunk 1]
```diff
@@ -8,11 +8,28 @@ public class DCLBuilderTranslateGizmo : DCLBuilderGizmo
...
+            if (snapFactor > 0)
+                initialEntityPosition = GetPositionRoundedToSnapFactor(entityTransform.position, axisValue);
+
             Vector3 move = activeAxis.transform.forward * axisValue;
-            Vector3 position = entityTransform.position + move;
+            Vector3 position = initialEntityPosition + move;
+
             entityTransform.position = position;
 
             return axisValue;
```
Comment (pbosio) [inline unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderTranslateGizmo.cs:20]: I have concerns about these changes because this code is shared with the builder dapp

Comment (pbosio) [reply unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderTranslateGizmo.cs:20]: I'll approve this. Let's revisit it if there is a issue next time builder needs an update

**Review by pbosio — APPROVED** [review]

**Review by pravusjif — APPROVED** [review]
