### PR TITLE
Errors only show when there are no fallbacks anymore (Asset Promises Handling)

### LINKED ISSUE #4000: System.Exception: The url https://content-assets-as-bundle.decentraland.org/v23/QmY3fLcWPwy7ijGm7Mk8SEExWALWDzPQN8X...
Sentry Issue: [UNITY-RENDERER-1H](https://sentry.io/organizations/decentraland/issues/3863869251/?referrer=github_integration)

```
System.Exception: The url https://content-assets-as-bundle.decentraland.org/v23/QmY3fLcWPwy7ijGm7Mk8SEExWALWDzPQN8XxSAvLmb2MPb has failed
```

### LINKED ISSUE #4002: System.Exception: Request failed? HTTP/1.1 404 Not Found ... https://content-assets-as-bundle.decentraland.org/v23/...
Sentry Issue: [UNITY-RENDERER-1D](https://sentry.io/organizations/decentraland/issues/3863866888/?referrer=github_integration)

```
System.Exception: Request failed? HTTP/1.1 404 Not Found ... https://content-assets-as-bundle.decentraland.org/v23/bafybeid5yggcwo2jnjndaxmvg5rndlaq6urb4iz5cgakdx6alvzeqfozbi
```

### PR DESCRIPTION
**Pull request by PalauiDCL**
fixes #4002 
fixes #4000 

## Error handling for asset Promises

The error handling has been centralized in the Rendereable Loader, for it, some expected exceptions thrown form separate promises have been removed and tests have been updated accordingly.

- After this PR, when an asset promise fails, the exception will only be called if there are no fallbacks. (A fallback is a different type of loading that will try to get the asset).
- If a fallback exists, the exception can be seen enabling VERBOSE
- If there are no more fallbacks, the exception should be shown as usual.

## QA
I am unsure if QA does work with sentry or error handling, if it does not, this PR should be ignored by the QA team.

### CODE REVIEW

**Review by Kinerius — APPROVED** [review]
I'm approving since this change is simple enough.
Still, the whole `RendereableAssetLoadHelper` class needs a good refactor where each load process has its own class, probably with an interface called `IAssetLoader` and a `WithFallback(IAssetLoader)` method.

If you are willing to make the change request my review again.

---- Answer Edit
@Kinerius I think this PR should be closed because the proposed change is outside the scope of this sprint, story points should be modified, some research would be needed and the task would mutate considerably.
For this reason I propose closing this PR (thus completing the two associated tasks) and prepare the refactor task for the next sprint (or when decided by the team).

I would like to hear @m3taphysics opinion on this before closing though!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs [hunk 1]
```diff
@@ -142,8 +142,7 @@ public IEnumerator FailCorrectlyWhenLoadingABWithoutGameObjects()
 
             yield return prom;
 
-            Assert.IsTrue(failed == true, "The broken paladin AssetBundle contains no GameObjects and should fail!");
-            LogAssert.Expect(LogType.Exception, new Regex("^.*?AB sub-promise asset or container is null"));
+            Assert.IsTrue(failed, "The broken paladin AssetBundle contains no GameObjects and should fail!");
```
Comment (eordano) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs:145]: Wtf is a broken paladin, can we improve this error log?

**Review by eordano — APPROVED** [review]
I am afraid this might lead to missed warnings, but on the other hand, we get a lot of complaints from SDK users regarding these 404 errors polluting the debug console on web.

The goal of having this in the sprint was to clean up the sentry logs -- I think this PR accomplishes that goal.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs (hunk 1 above)
Comment (PalauiDCL) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs:145]: The person that did the tests in the past, decided to use this "Broken Paladin" as a test that should fail because it does not exist.
We can change it but, as is a test for "FailCorrectly", has no interference in the project in any case.

**Comment by m3taphysics** [comment]
> I'm approving since this change is simple enough. Still, the whole `RendereableAssetLoadHelper` class needs a good refactor where each load process has its own class, probably with an interface called `IAssetLoader` and a `WithFallback(IAssetLoader)` method.
> 
> If you are willing to make the change request my review again.
> 
> ---- Answer Edit @Kinerius I think this PR should be closed because the proposed change is outside the scope of this sprint, story points should be modified, some research would be needed and the task would mutate considerably. For this reason I propose closing this PR (thus completing the two associated tasks) and prepare the refactor task for the next sprint (or when decided by the team).
> 
> I would like to hear @m3taphysics opinion on this before closing though!

I think this is fine to close if the error logs are now cleaned up (only actual missing assets are logged). My proposal for a refactor would be that assets have a manifest file so that we know where to load them from, I am not a fan of just "falling back" especially with endpoints which take "seconds" to determine if something exists or not.
