### PR TITLE
Fix: hiccups when opening the explore menu

### LINKED ISSUE #2061: Reduce hiccups when opening the explore menu
Whenever you open the explore menu, there are many hiccups while loading different elements of the ui.
We can try to reduce them by doing some throttling while creating elements and filling the ui. Regarding to api json data parsing, we could use threads on desktop implementation and throttling on web builds (or just throttling for both if its simpler).

### PR DESCRIPTION
**Pull request by popuz**
## What does this PR change?
Fix #2061 

- Replaced `GameObject.SetActive` by `Canvas.enabled` logic for subSections
- Replaced instant loading of cards with sequential loading (throttling) - for initial loading and also for LoadMore button logic
- Refill Pools when they get emptied (also with throttling)
- Removed SpriteMeshGeneration on sprite creation
- Moved logic of hiding loading bar from Controller inside View

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=bug/hiccups-when-opening-the-explore-menu
2. Open ExploreV2 events section
3. Switch between Highlights->Places->Events
4. Press LoadMore button in Places and Events
5. Observe improved performance

Devs-only: you can compare all 3 main improved behaviours with profiling current Dev and this branch. Main behaviours
- Initial loading of cards (for Highlights and Places are easier to check, because Events almost loaded immidiatly)
- Switching between subSections
- Loading More button behaviour

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs [hunk 1]
```diff
@@ -113,6 +113,18 @@ private PoolableObject Extract()
             return po;
         }
 
+        public async UniTask IterativePrewarm(int prewarmCount)
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs:116]: I would call it `AsyncPrewarm`. We need a cancellation token here to dispose this task properly if the caller is disposed as well.

It can also mess up with a normal prewarming right? how is that edge case handled?

File: unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs [hunk 2]
```diff
@@ -150,7 +150,8 @@ public virtual void OnLoseFocus()
     public virtual void Dispose()
     {
         DataStore.i.screen.size.OnChange -= OnScreenSizeModified;
-        if (!isDestroyed)
+        
+        if (!isDestroyed && !Application.isEditor)
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs:154]: Why are we avoiding destruction in `Editor`?

File: unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs [hunk 3]
```diff
@@ -1,5 +1,6 @@
 using DCL.Helpers;
 using System;
+using UnityEditor.Sprites;
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs:3]: this wont work on build. Are we using it?

**Review by AjimenezDCL — CHANGES_REQUESTED** [review]

File: unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs (hunk 3 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs:3]: nice catch. It was unused `using` :) Probably, I was using some Editor API to get rid of the Sprite MeshGeneration call but then found another way. Will remove it

File: unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs (hunk 2 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs:154]: it is mainly to remove Console error logs asking to use `DestroyImmidiate`. But I can use `#if UNITY_EDITOR` if you prefer. Here is the log
```
Destroy may not be called from edit mode! Use DestroyImmediate instead.
Destroying an object in edit mode destroys it permanently.
UnityEngine.Object:Destroy (UnityEngine.Object)
BaseComponentView:Dispose () (at Assets/UIComponents/Scripts/Components/BaseComponentView.cs:155)
```

Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs:154]: I made a refactoring for this, by hiding  #if UNITY_EDITOR inside `DestroyInternally` method. It was quite clean, but then a lot of tests cases were falling, so I reverted to this solution :(

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs [hunk 4]
```diff
@@ -1,150 +1,24 @@
...
+    private const int FEATURED_EVENT_CARDS_POOL_PREWARM = 10;
+    private const string TRENDING_EVENT_CARDS_POOL_NAME = "Events_TrendingEventCardsPool";
+    private const int TRENDING_EVENT_CARDS_POOL_PREWARM = 12;
+    private const string UPCOMING_EVENT_CARDS_POOL_NAME = "Events_UpcomingEventCardsPool";
+    private const int UPCOMING_EVENT_CARDS_POOL_PREWARM = 9;
+    private const string GOING_EVENT_CARDS_POOL_NAME = "Events_FeatureGoingEventCardsPool";
+    private const int GOING_EVENT_CARDS_POOL_PREWARM = 9;
+
+    private readonly Queue<Func<UniTask>> cardsVisualUpdateBuffer = new Queue<Func<UniTask>>();
+    private readonly Queue<Func<UniTask>> poolsIterativePrewarBuffer = new Queue<Func<UniTask>>();
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/ExploreV2/Scripts/Sections/PlacesAndEventsSection/SubSections/EventsSubSection/EventsSubSectionMenu/EventsSubSectionComponentView.cs:21]:
```suggestion
    private readonly Queue<Func<UniTask>> poolsIterativePrewarmBuffer = new Queue<Func<UniTask>>();
```

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs [hunk 5]
```diff
@@ -60,7 +60,7 @@ public interface ICarouselComponentView
     /// Adds a new item in the carousel.
     /// </summary>
     /// <param name="item">An UI component.</param>
-    void AddItem(BaseComponentView item);
+    void AddItemWithDotsSelector(BaseComponentView item);
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:63]: Please, lets modify the current documentation that we have in notion about the `Carousel` UI Component: https://www.notion.so/decentraland/UI-Components-Reference-f467a8d05d594718a2c12809dcfaf132?p=328f41bff9e2416da2d7372a2d004bfc&pm=s

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs [hunk 6]
```diff
@@ -265,13 +268,16 @@ public void SetItems(List<BaseComponentView> items)
...
-    public void AddItem(BaseComponentView item)
+    public void AddItemWithDotsSelector(BaseComponentView item)
     {
         CreateItem(item, $"Item{instantiatedItems.Count}");
         SetManualControlsActive(model.showManualControls);
         GenerateDotsSelector();
     }
-
+    
+    public void AddItem(BaseComponentView item) =>
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:278]: We should add the `AddItem` method into the `ICarouselComponentView` interface, right?

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs [hunk 7]
```diff
@@ -565,7 +573,7 @@ internal IEnumerator RunAnimationCoroutine(CarouselDirection direction, int numb
         isInTransition = false;
     }
 
-    internal void GenerateDotsSelector()
+    public void GenerateDotsSelector()
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:576]: Why this method has to be `public`? Is it used out of this class?

File: unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs [hunk 8]
```diff
@@ -65,7 +65,7 @@ public interface IGridContainerComponentView
     /// Adds a new item in the grid.
     /// </summary>
     /// <param name="item">An UI component.</param>
-    void AddItem(BaseComponentView item);
+    void AddItemWithResize(BaseComponentView item);
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs:68]: Please, lets update it in the documentation we have about `GridContainer` UI Component in notion: https://www.notion.so/decentraland/UI-Components-Reference-f467a8d05d594718a2c12809dcfaf132?p=5a29ed52bfc34987b627e1fd7ec546b5&pm=s

File: unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs [hunk 9]
```diff
@@ -370,11 +370,17 @@ public void SetItems(List<BaseComponentView> items)
...
     {
         CreateItem(item, $"Item{instantiatedItems.Count}");
         SetItemSize(model.itemSize);
     }
+    
+    public void SetItemSizeForModel() =>
+        SetItemSize(model.itemSize);
+    
+    public void AddItem(BaseComponentView item) => 
+        CreateItem(item, $"Item{instantiatedItems.Count}");
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs:383]: We should add the `SetItemSizeForModel` and `AddItem` methods into the `IGridContainerComponentView` interface, right? And also update it in the notion documentation.

File: unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs [hunk 10]
```diff
@@ -436,7 +442,7 @@ internal void CreateItem(BaseComponentView newItem, string name)
         instantiatedItems.Add(newItem);
     }
 
-    internal void ResizeGridContainer()
+    public void ResizeGridContainer()
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs:445]: Is it needed to be `public`?

File: unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs [hunk 11]
```diff
@@ -101,7 +108,9 @@ public override void Dispose()
         currentUriLoading = null;
         lastLoadedUri = null;
         imageObserver.RemoveListener(OnImageObserverUpdated);
-        Destroy(currentSprite);
+
+        if (!Application.isEditor)
+            Destroy(currentSprite);
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/UIComponents/Scripts/Components/Image/ImageComponentView.cs:113]: Why we don't destroy the sprite in editor?

**Review by sandrade-dcl — CHANGES_REQUESTED** [review]
Great work! I'm testing the build and I notice the improvement navigating through the explorer menu ❤️ I left some comments.

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs (hunk 7 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:576]: For performance consideration, I wanted to generate Dots only after all Items were added asynchronously in `HighlightsSubSectionComponentView `or in `EventsSubSectionComponentView `(and not after each one was added). Thus, these 2 classes calls this method after getting all Items added

File: unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs (hunk 9 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs:383]: to my surprise, there are no clients of this interface at all in the project. Only one implementation, which is `GridContainerComponentView`. So I don't know if it makes sense to add it to the interface 🤔 We need refactoring, where we will replace usage of `GridContainerComponentView `with interface `IGridContainerComponentView `or we need to remove this interface.

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs (hunk 7 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:576]: a similar idea was behind presenting public `SetItemSizeForModel` in `GridComponentView` - to resize container after all Items were added/set

File: unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs (hunk 9 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/UIComponents/Scripts/Components/GridContainer/GridContainerComponentView.cs:383]: Oh, it's true... I remember that this view was directly referenced from a parent prefab. I guess we could refactor it in order to avoid this direct reference and to work with the interface, but maybe it should be for a separated implementation.

File: unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs (hunk 5 above)
Comment (popuz) [reply unity-renderer/Assets/UIComponents/Scripts/Components/Carousel/CarouselComponentView.cs:63]: I will. However, I see that it is in the Archive folder:)

**Review by sandrade-dcl — APPROVED** [review]

File: unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs (hunk 2 above)
Comment (AjimenezDCL) [reply unity-renderer/Assets/UIComponents/Scripts/Components/BaseComponentView.cs]: I think we are hiding an underlying issue. We are getting that `DestroyImmediate` log because that destruction is happening after PlayMode is stopped, that shouldn't happen.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs [hunk 12]
```diff
@@ -113,6 +112,18 @@ private PoolableObject Extract()
...
+        public async UniTask PrewarmAsync(int prewarmCount, CancellationToken cancellationToken)
+        {
+            if (unusedObjects.Count >= prewarmCount)
+                return;
+                
+            for (int i = 0; i < prewarmCount; i++)
+            {
+                Instantiate();
+                await UniTask.NextFrame(cancellationToken);
+            }
```
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs:124]: I would add a 
`cancellationToken?.ThrowIfCancelled` at the beginning of the method to avoid starting with a cancelled token.

**Review by AjimenezDCL — APPROVED** [review]
Approving with a nitpicking request
