### PR TITLE
fix: BiW scale tool is not working correctly

### LINKED ISSUE #316: Scale gizmos on all axis is not working correctly
Scale gizmos is working strange when you try to scale in the three axis at the same time

### LINKED ISSUE #317: Scale on Z axis with multiple entities
If you have multiple entities selected and scale in the Z axis, they move as well when they should only scale

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## Fixed bugs
- [x] **Scale gizmos on all axis is not working correctly** (Fixes #316)
_Scale gizmos is working strange when you try to scale in the three axis at the same time_
- [x] **Scale on Z axis with multiple entities** (Fixes #317)
_If you have multiple entities selected and scale in the Z axis, they move as well when they should only scale_

## Testing
1. Go to: https://play.decentraland.zone/?index.html&renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-scale-is-not-working-correctly&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
2. Press `K` to open the Builder In World editor.

### CODE REVIEW

**Review by Suduck — APPROVED** [review]

**Comment by Suduck** [comment]
Good job!

File: unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderScaleGizmo.cs [hunk 1]
```diff
@@ -22,12 +24,38 @@ public override void Initialize(Camera camera, Transform cameraTransform)
         public override void SetSnapFactor(DCLBuilderGizmoManager.SnapInfo snapInfo) { snapFactor = snapInfo.scale; }
 
         public override float TransformEntity(Transform entityTransform, DCLBuilderGizmoAxis axis, float axisValue)
+        {
+            // In order to avoid to make the scale of each selected entity dependent of the 'entityTransform' parent,
+            // we temporally move all entities to the local position (0,0,0) before calculate the new scale.
+            foreach (Transform entity in entityTransform)
+            {
+                entitiesOriginalPositions.Add(entity, entity.transform.position);
+                entity.transform.localPosition = Vector3.zero;
```
Comment (pravusjif) [inline unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderScaleGizmo.cs:33]: this should be `position` instead of `localPosition` right? let's use the same position term to be consistent, even though probably in this case `poition` and `localPosition` do the same thing if the entity doesn't have a parent GO

**Review by pravusjif — APPROVED** [review]

File: unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderScaleGizmo.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Builder/Scripts/Gizmos/DCLBuilderScaleGizmo.cs:33]: But in this case I want to set its local position, not the world one, because the entity has a parent and I want to place temporally the child to the (0,0,0) position relative to the parent.
