### PR TITLE
fix: added avatar name in hide gameobject list

### LINKED ISSUE #1782: Nametags are still visible in avatar modifier area HIDE_AVATARS
The avatar modifier area HIDE_AVATARS should hide the player avatar and its nametag.

### PR DESCRIPTION
**Pull request by DavideJensen**
## What does this PR change?

Fix #1782
Hides avatar names in HIDE_AVATARS modified areas

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=fix/hide-nametags-in-modifier&position=-134%2C74
2. Go to the tennis court inside
3. Verify that other players are entirely hidden and even their name disappears

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs [hunk 1]
```diff
@@ -221,7 +221,7 @@ private void InitializeAvatarAudioAndParticleHandlers(GameObject container, Anim
     {
         //NOTE(Mordi): Adds handler for animation events, and passes in the audioContainer for the avatar
         AvatarAnimationEventHandler animationEventHandler = createdAnimation.gameObject.AddComponent<AvatarAnimationEventHandler>();
-        AudioContainer audioContainer = container.transform.parent.parent.GetComponentInChildren<AudioContainer>();
+        AudioContainer audioContainer = container.transform.parent.parent.parent.GetComponentInChildren<AudioContainer>();
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs:224]: parent.parent.parent doesn't look, can we try to get gameobject reference that has the AudioContainer somehow?

**Review by Suduck — APPROVED** [review]
Approved but If there is a way to address the issue I encourage you to do it!

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs (hunk 1 above)
Comment (AjimenezDCL) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs:224]: This is super ugly but fortunately it will dissapear once #1567 is merged.

**Review by AjimenezDCL — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs (hunk 1 above)
Comment (AjimenezDCL) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs:224]: It doesn't really matter, this is going to get removed once the new avatar merges (which is imminent)

Comment (DavideJensen) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs:224]: Yeah i've seen that ugly thing, I looked a bit around and it felt like there was the need of a big refactoring to avoid that parent chain, I didn't really feel confident in making big changes to avoid that, if the avatar merge solves it perfect, otherwise I'll open a technical debt issue with that
