### PR TITLE
fix: show guest panel only when trying to add friend from passport

### LINKED ISSUE #4654: Remove wallet gating when viewing other avatar passports
The following modal should only open when the user clicks on an action that requires to be logged in. For example when the user clicks on add friend or send a message.

Additionally, make sure closing the modal does not close the passport.

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #4654
Adds the guest panel notification only when trying to add friend in passport and not in passport open

...

## How to test the changes?

1. Launch the explorer as a guest https://play.decentraland.org/?explorer-branch=fix/guest-panel-passport
2. Open a passport
3. Check the passport can be used
4. Press add friend
5. verify that the guest panel appears
_______
1. Launch the explorer as a regular user https://play.decentraland.org/?explorer-branch=fix/guest-panel-passport
2. verify that the passport works as always

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs [hunk 1]
```diff
@@ -272,6 +278,12 @@ private void ReportUser()
 
         private void WhisperUser(string userId)
         {
+            if (userProfileBridge.GetOwn().isGuest)
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Passport/Passport/PlayerInfo/PassportPlayerInfoComponentController.cs:281]: we should add test coverage for this case

**Review by lorux0 — CHANGES_REQUESTED** [review]

**Review by kwsskulinski — APPROVED** [review]
Modal appears when player tries to select add friend not as they opened the wallet. Everything in the wallet is fully viewable to the guest account.

**Review by lorux0 — APPROVED** [review]
