### PR TITLE
fix: gltf added to library more than once

### LINKED ISSUE #1205: Add test for PR #1194
PR #1194

### PR DESCRIPTION
**Pull request by pbosio**
related to PR https://github.com/decentraland/unity-renderer/pull/1194 (refactored changes done there)
related to issue #1196 

In some situations GLTFs were added more than once to the library sometimes leaving orphan GLTF and wasting memory unnecessarily 

also: closes #1205 by adding test coverage

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs [hunk 1]
```diff
@@ -4,9 +4,40 @@ public class AssetPromiseKeeper_GLTF : AssetPromiseKeeper<Asset_GLTF, AssetLibra
...
+
         public AssetPromiseKeeper_GLTF() : base(new AssetLibrary_GLTF()) { }
 
-        protected override void OnSilentForget(AssetPromise_GLTF promise) { promise.OnSilentForget(); }
+        protected override void OnSilentForget(AssetPromise_GLTF promise)
+        {
+            promise.OnSilentForget();
+        }
+
+        public override AssetPromise_GLTF Forget(AssetPromise_GLTF promise)
```
Comment (BrianAmadori) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs:15]: Please let's not add a new band aid and try to fix the issue in the original `Forget` implementation. If we need to do this because we are expanding the "hack" of not being able to fix the cancelled promises, this is wrong and we need to revisit the core of the issue to make the promises truly cancellable. 

Band aids over band aids are what usually make a system no more maintainable to the point that everything has to be implemented from scratch.

Comment (pbosio) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs:15]: Agree. But to make promises fully cancellables we should refactor a lot of the GLTF plugin and right now we are having a lot of issues regarding GLTF handling in prod. So maybe Band aids is not an entirely wrong decision for now 🤷‍♂️

Comment (BrianAmadori) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromiseKeeper_GLTF.cs:15]: As this is unit-tested, we agreed offline to give this solution a pass. We should very soon remove this code and implement proper cancelling for the `GLTFSceneImporter`.

**Review by Suduck — APPROVED** [review]

**Review by BrianAmadori — APPROVED** [review]
Did a quick test run and did not found any obvious issues. Approving.
