### PR TITLE
fix: change avatar modifier warning position for worlds

### LINKED ISSUE #5469: The features' restricter's warning is placed in a wrong position for Worlds
In worlds you dont have the minimap but we have the warning floating in the middle of the screen, when its position should be up against the margin.

### Steps to reproduce
1. Go to: https://play.decentraland.org/?realm=8metagames.dcl.eth&position=2%2C1
2. Observe the issue.

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
Fix #5469 

When we were in a world where the change avatar modifier warning was activated, we had HUD floating wrongly in the middle of the screen:

image
image

Now, in this case, this HUD is changing its position so when we are in a normal land it keeps its original position and when we are in a world it changes its position to the top-side of the screen:

image
image

## How to test the changes?
1. Launch the explorer
2. Go to any non-world place where the avatar modifier warning HUD is activated (for example WonderMine, near the machine).
3. Observe the warning is well placed by the minimap.
4. Go to any world place (for example: `8metagames.dcl.eth`).
5. Observe the warning is well placed in the top-left of the screen, under the [GO TO GENESIS CITY] button.
6. Go again to any non-world place where the avatar modifier warning HUD is activated (for example WonderMine, near the machine).
7. Observe the warning is well placed by the minimap.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at fcb54b2</samp>

The pull request modifies the `AvatarModifierAreaFeedbackHUD` prefab and its related scripts and tests to support different feedback modes depending on the world mode. The world mode is a boolean value that indicates whether the user is in a land or a world. The pull request adds a `DataStore_Common` argument to the `AvatarModifierAreaFeedbackController` and `AvatarModifierAreaFeedbackPlugin` classes to access and subscribe to the world mode changes. The pull request also adds a `SetWorldMode` method to the `IAvatarModifierAreaFeedbackView` interface and implements it in the `AvatarModifierAreaFeedbackView` class to adjust the HUD elements accordingly.

### CODE REVIEW

**Review by anicalbano — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackController.cs [hunk 1]
```diff
@@ -1,21 +1,33 @@
...
+            BaseRefCounter<AvatarModifierAreaID> avatarAreaWarnings,
+            IAvatarModifierAreaFeedbackView view,
+            DataStore_Common commonDataStore)
         {
             this.view = view;
             view.SetUp(avatarAreaWarnings);
+
+            this.commonDataStore = commonDataStore;
+            commonDataStore.isWorld.OnChange += OnWorldModeChange;
+            OnWorldModeChange(DataStore.i.common.isWorld.Get(), false);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarModifierAreaHUD/Scripts/AvatarModifierAreaFeedbackController.cs:19]: use the datastore passed in the parameter instead of referring to the singleton

**Review by lorux0 — CHANGES_REQUESTED** [review]

**Review by lorux0 — APPROVED** [review]
