### PR TITLE
fix: ab not loading with new cdn flow for worlds

### LINKED ISSUE #4558: New onboarding scene is not properly converted to asset bundles
When launching new onboarding, the assets on the scene are not converted to asset bundles, resulting in a longer load.

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Closes #4558 after enabling the new feature flag `AB-NEW-CDN`

When loading worlds the scene-id has a different format so we had to fix this case to get the correct entity id to load the asset bundles with the new CDN flow

image

## How to test the changes?

- Go to: https://play.decentraland.org/?explorer-branch=fix/new-cdn-worlds&ENABLE_AB-NEW-CDN&realm=dclonboarding.dcl.eth
- use `/detectabs` chat command 
- Check that most/all assets should be green ( blue for the colliders ) 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by kwsskulinski — APPROVED** [review]
Most of the assets are green as expected.

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs [hunk 1]
```diff
@@ -18,14 +18,29 @@ public class SceneAbDto
...
         private Service<IWebRequestController> webRequestController;
 
         private Action onSuccess;
 
-        public AssetPromise_SceneAB(string contentUrl, string hash) : base(contentUrl, hash)
+        public AssetPromise_SceneAB(string contentUrl, string sceneId) : base(contentUrl, sceneId)
         {
             cancellationTokenSource = new CancellationTokenSource();
+            this.hash = GetEntityIdFromSceneId(sceneId);
+            Debug.Log(this.hash);
```
Comment (sandrade-dcl) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs:31]: Is this debug log intentional?

**Review by sandrade-dcl — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs (hunk 1 above)
Comment (Kinerius) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/SceneAB/AssetPromise_SceneAB.cs]: heh no, deleting it
