### PR TITLE
fix: Floor loading placeholder is visible after the floor is loaded s…

### LINKED ISSUE #342: Floor loading placeholder is visible after the floor is loaded sometimes
If the floor is not loaded and you try to load another floor, the loading placeholder of the first floor will stay

We should ensure that there is no loading placeholder after all the floors has been loaded

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What this PR includes?
- **BUG FIX:** "Floor loading placeholder is visible after the floor is loaded sometimes" (Fixes #342)
_If the floor is not loaded and you try to load another floor, the loading placeholder of the first floor will stay._

## How to test it?
1. Go to: https://play.decentraland.zone/?index.html&renderer=urn:decentraland:off-chain:renderer-artifacts:fix/BiW-Floor-loading-placeholder-is-visible-after-the-floor-is-loaded-sometimes&ENV=zone&ENABLE_BUILDER_IN_WORLD&position=100,100
2. Press `K` to open the Builder In World editor.
3. Open the catalog panel (right side of the screen).
4. Select different floors several times in a row without letting them finish loading.
5. Notice that the loading spinner is always being hidden after the last floos has been loaded.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]

**Review by BrianAmadori — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs [hunk 1]
```diff
@@ -92,6 +92,7 @@ public void CreateFloor(CatalogItem floorSceneObject)
         {
             DCLBuilderInWorldEntity decentralandEntity = biwCreatorController.CreateCatalogItem(floorSceneObject, WorldStateUtils.ConvertPointInSceneToUnityPosition(initialPosition, parcel), false, true);
             decentralandEntity.rootEntity.OnShapeUpdated += OnFloorLoaded;
+            dclBuilderMeshLoadIndicatorController.HideAllIndicators();
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs:95]: This won't work in a scene with severals parcels since it will hide the loading indicators of the previous instanciated placeholders. 

I think a better approach will be to delete the complete loading placeholder when deleting the previous floor entities, this way we are not only hiding the indicators but also removing the placeholder that will stay in the world

**Review by Suduck — CHANGES_REQUESTED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs (hunk 1 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BIWFloorHandler.cs]: You're right, thanks for the warning! I have changed the approach, you can see it in https://github.com/decentraland/unity-renderer/pull/358/commits/d4125b1ce8409eb8166fce5e8b46d716a4fe546b

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs [hunk 2]
```diff
@@ -709,6 +710,7 @@ public void DeleteEntity(DCLBuilderInWorldEntity entityToDelete, bool checkSelec
         hudController?.RefreshCatalogAssetPack();
         EntityListChanged();
         builderInWorldBridge?.RemoveEntityOnKernel(idToRemove, sceneToEdit);
+        OnEntityDeleted?.Invoke(entityToDelete.rootEntity.entityId);
```
Comment (Suduck) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs:713]: I think this event should be before the line 787, since we destroy the entity gameObject it can be null, also, if someone want to do changes on the entity before it gets finally delete it should be able to do it!

**Review by Suduck — APPROVED** [review]

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs (hunk 2 above)
Comment (sandrade-dcl) [reply unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Controllers/BuilderInWorldEntityHandler.cs]: Ok, done in https://github.com/decentraland/unity-renderer/pull/358/commits/ea850879045eb077e80380241672a91a48801b4b
