### PR TITLE
fix: animation states not being correctly updated

### LINKED ISSUE #2856: Movement animations missing after changing wearables in the backpack
Description:
Movement animations for the player avatar go missing once a wearable is changed from the backpack menu.

Steps to reproduce:
1. Log in to the game.
2. Open up the backpack and change one of the wearables from any category and press "Done".
3. Use the movement keys to move the player avatar around.
5. Observe the player avatar.

Results:
Player avatar's movement animations disappear after changing a wearable in the backpack.

Expected results:
Player avatar's movement animations stay the same after changing a wearable in the backpack.

Notes:
-Platforms: Windows web, dev branch
-Please see the attached video for reference.
https://images.zenhubusercontent.com/337227404/e7619a7d-3f1d-4f5e-b630-5980c32c8714/2022_08_16_12_20_09.mp4

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Fixes #2856

## How to test the changes?

Change any wearable then try running, animations should work as expected.

We should also test if it works when another character changes a wearable, do we see it correctly being animated? 

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

File: unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs [hunk 1]
```diff
@@ -119,13 +118,20 @@ public bool Prepare(string bodyshapeId, GameObject container)
...
-            Environment.i.platform.updateEventHandler.AddListener(IUpdateEventHandler.EventType.Update, OnEventHandlerUpdate);
+            isUpdateRegistered = true;
+
+            if (isOwnPlayer)
+            {
+                DCLCharacterController.i.OnUpdateFinish += OnUpdateWithDeltaTime;
+            }
+            else
+            {
+                Environment.i.platform.updateEventHandler.AddListener(IUpdateEventHandler.EventType.Update, OnEventHandlerUpdate);
```
Comment (lorux0) [inline unity-renderer/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs:132]: to avoid subscribing twice can you do something like: `Environment.i.platform.updateEventHandler.RemoveListener(IUpdateEventHandler.EventType.Update, OnEventHandlerUpdate);` ?

**Review by lorux0 — APPROVED** [review]
